# Generated by Django 4.1.2 on 2023-03-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(choices=[('1', models.CharField(max_length=255, verbose_name='Answer 1')), ('2', models.CharField(max_length=255, verbose_name='Answer 2')), ('3', models.CharField(max_length=255, verbose_name='Answer 3')), ('4', models.CharField(max_length=255, verbose_name='Answer 4'))], default='1', max_length=1, verbose_name='Correct Answer'),
        ),
    ]
