# Generated by Django 4.1.6 on 2023-02-27 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.question', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(blank=True, help_text='Title', max_length=255, null=True, verbose_name='Title'),
        ),
    ]
