# Generated by Django 4.1.6 on 2023-02-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_quiz_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('0', 'Beginner'), ('1', 'Intermediate'), ('2', 'Advanced')], default='Intermediate', max_length=20, verbose_name='Difficulty'),
        ),
    ]
