# Generated by Django 4.1.6 on 2023-02-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_answer_question_quiz_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('0', 'Beginner'), ('1', 'Intermidiate'), ('2', 'Advanced')], default='Intermidiate', max_length=20, verbose_name='Difficulty'),
        ),
    ]
