# Generated by Django 4.1.6 on 2023-02-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('0', 'Beginner'), ('1', 'Intermediate'), ('2', 'Advanced')], default='0', max_length=20, verbose_name='Difficulty'),
        ),
    ]
