# Generated by Django 4.1.6 on 2023-02-27 09:55

import django.core.validators
from django.db import migrations, models
import users.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(help_text='Username', max_length=150, unique=True, verbose_name='Username')),
                ('name', models.CharField(help_text='John Doe', max_length=150, verbose_name='Full name')),
                ('email', models.EmailField(blank=True, error_messages={'unique': 'A user with that email already exists.'}, help_text='johndoe@example.com', max_length=250, null=True, unique=True, validators=[django.core.validators.EmailValidator], verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, help_text='Phone number', max_length=15, null=True, verbose_name='Phone number')),
                ('is_active', models.BooleanField(default=True, help_text='Active', verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, help_text='Staff', verbose_name='Staff')),
                ('is_superuser', models.BooleanField(default=False, help_text='Superuser', verbose_name='Superuser')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
    ]
