# Generated by Django 4.1.6 on 2023-02-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'A user with that email already exists.'}, help_text='johndoe@example.com', max_length=250, null=True, unique=True, verbose_name='Email'),
        ),
    ]
