# Generated by Django 4.1.6 on 2023-02-27 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(blank=True, help_text='Email', max_length=255, null=True, unique=True, validators=[django.core.validators.EmailValidator], verbose_name='Email'),
        ),
    ]
